### ISSUE TITLE
Input de ejemplo T1

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2133-PUC/2022-1#100]
El input inicial de ejemplo en la T1 es:
3
2
51 414 23 104
24 1 32 52
4
PATH 10
DEEP 104
DESTROY 23
ORDER

Se pide destruir el nodo con value 23 pero el value en cuestión es el 3ero (inatorness) que no tiene valor 23. Se puede pedir destruir un value que no esta? o es un error?

Gracias!

**Comment by etoteiza** [comment]
Si, se puede pedir destruir un value que no está. Debes implementar lo necesario para considerar dicho caso.

**Comment by ignaciomansuy** [comment]
@etoteiza
entonces qué se debe poner el output en caso de que el valor entregado no exista? Porq en el enunciado no dice nada sobre ese caso

**Comment by etoteiza** [comment]
Se pide como output el número de nodos destruidos, que en este caso sería 0.
