### ISSUE TITLE
Borrando dos veces el mismo nodo: free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2133-PUC/2022-1#101]
Hola, en el DESTROY nos piden eliminar un nodo y sus hijos. 
Para esto, entro al nodo y a sus hijos recursivamente y luego elimino el nodo en cuestión. (free(node))

Pero cuando imprimo el arbol, los nodos que ya borré me tiran datos random como si existieran todavia.

Y cuando intento eliminar lo que queda de arbol me dice "free(): double free detected in tcache 2" como si estuviera borrando algo que ya borre.

Como puedo solucionar esto? Gracias

**Comment by etoteiza** [comment]
¿Puede ser que en el árbol sigas teniendo el puntero del nodo a destruir (que ya liberaste)?

**Comment by JoseTomasSoto** [comment]
Puede ser pq solo hago un free(node) recursivo que va borrando todo el subarbol, pq esto no es suficiente? Que mas tendria que hacer?

**Comment by carolinamaggi** [comment]
@JoseTomasSoto lo voy a poner como ejemplo con las listas ligadas, si tu liberas el tail, tienes que asegurarte de que el nodo anterior quede como tail y que apunte a NULL, si no le dices que apunte a NULL, sigue apuntando al lugar donde estaba el tail aunque lo liberes

**Comment by JoseTomasSoto** [comment]
yaa gracias, ahi lo intente y puse nodo->left = NULL, una vez ya elimino al hijo pero tengo error en valgrind  del tipo Invalid read
