### ISSUE TITLE
[T1] - Parte 1 

### ISSUE THREAD

**Issue by franciscares** [IIC2133-PUC/2022-1#103]
Hola!
El BST de la primera parte, ¿debe estar balanceado? y ¿debe quedar balanceado cuando se ejecute DESRTOY?

**Comment by sebastianbreguel** [comment]
No, no debe estar balanceado, debe funcionar como BST clasico, NO DEBEN BALANCEARLO, debe estar en base al orden de los inputs. 

Tambien al momento de ejercutar el destroy, notar que te piden hacer destroy a el arbol donde el nodo que te dicen, es el nodo padre. Por lo que no deberia sufrir cambios el BST que estaba antes del DESTRO nodo_x.
