### ISSUE TITLE
Error Instalación GTK - Mac

### ISSUE THREAD

**Issue by cfernandek** [IIC2133-PUC/2022-1#104]
Hola! no puedo instalar GTK + en. mi computador (Mac), siguiendo la guía de instalación subida por el curso, me aparece el siguiente error. Existe otra forma de instalarlo? o alguna forma de solucionar el error? Gracias.
<img width="848" alt="Captura de Pantalla 2022-04-18 a la(s) 17 40 10" src="https://user-images.githubusercontent.com/69773929/163882416-81b9473a-f6a5-4ff3-ae76-0980f5680d7e.png">

**Comment by stgopau** [comment]
Yo tengo el mismo problema. Pudiste solucionarlo??

**Comment by cfernandek** [comment]
No todavía no puedo!
