### ISSUE TITLE
[T1 P2] Estructura a implementar

### ISSUE THREAD

**Issue by raibd** [IIC2133-PUC/2022-1#109]
Hola, en el enunciado se habla de un árbol BVH y que se recomienda utilizar el algoritmo BVH, sin embargo después sale que se recomienda implementar un KD-Tree. Esto me genera dudas ya que ambos son árboles. Se refieren a que hay que implementar el algoritmo BVH usando KD-Trees? O hay que elegir uno de estos árboles e implementarlo?

Gracias de antemano

**Comment by etoteiza** [comment]
Como se menciona en el enunciado en esa parte, eres libre de utilizar cualquier estructura que solucione el problema pedido, siempre y cuando, **no supere la complejidad pedida**
