### ISSUE TITLE
Error en VSCode corriendo C

### ISSUE THREAD

**Issue by airiquelme** [IIC2133-PUC/2022-1#11]
Holaa. Completé todo el setup para poder ejecutar C en mi computador windows, pero aunque funciona (me deja usar bash, compilar el programa, y ejecutarlo en la terminal) el detector de problemas de VSCode me indica que hay un error en "#include <stdio.h>".
Dice que falta o no encuentra un "incudePath", y que no se puede abrir el archivo de origen "<stdio.h>"... sin embargo se ejecuta bien?

Dejo esta issue porque aunque no parece estar dándome ningún problema hasta ahora, quiero evitar posibles problemas en el futuro al no tener ni idea cuál es el error. (Google no fue muy útil dándome soluciones)

**Comment by CarloGauss33** [comment]
Ese problema se debe a que vscode se esta ejecutando en windows, lo que provoca que vscode busque las librerias de C para windows y no para WSL como deberia. 
Para solucionar esto puedes usar la extension REMOTE-WSL que te permite abrir vscode dentro de wsl
