### ISSUE TITLE
[T1 P2] Duda para ver interfaz grafica

### ISSUE THREAD

**Issue by FelipeLara00** [IIC2133-PUC/2022-1#111]
Hola!
En la parte 2 de la tarea no he hecho cambios en los archivos y no me abre ninguna ventana de la interfaz. Seguí el set-up tal cual pero aun así no me funciona. Tampoco me tira errores solo me sale esto:
![image](https://user-images.githubusercontent.com/61998555/164916908-2356b5b0-4811-4aff-a72e-1b3968de7def.png)

**Comment by mjgarrido1** [comment]
No soy ayudante pero el archivo input.txt es un nombre descriptivo. Debes poner como input los archivos que estan dentro de la carpeta demo.

**Comment by carolinamaggi** [comment]
caché que lo solucionaste en discord :)
