### ISSUE TITLE
[T1] Destroy nodo y luego busqueda del mismo

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2133-PUC/2022-1#114]
Hola! Como se puede ver en la foto 1, en la línea 152605 se pide el destroy del nodo 1079. Esto implica que todos los nodos que cuelgan de este también deben ser destruídos. Por lo tanto, todos los nodos con el mismo valor (en este caso 1079) también serán destruidos (puesto que según el enunciado en caso de empate del valor de un nodo se debe conservar el orden del input). 
Según #94, el valor dado en el comando DEEP siempre existirá. Sin embargo, en los tests entregados no se cumple esto, como se muestra en las imágenes 2 y 3 adjuntas, puesto que todos los nodos con valor 1079 deberían haber sido destruídos.

![image](https://user-images.githubusercontent.com/64439029/165158064-12fedaab-be88-46f6-8ed7-daf099ef4cc6.png)

![image](https://user-images.githubusercontent.com/64439029/165158142-7eaba57f-310b-43ed-9bbf-8cb09af2bdc7.png)

![image](https://user-images.githubusercontent.com/64439029/165158183-753935b3-43f9-4f03-89a3-54663897dc94.png)

**Comment by sebastianbreguel** [comment]
Hola! Si estamos revisando ese error ahora mismo, solamente los tests hard presentaban un error. Les avisaremos cuando se actualicen los tests
