### ISSUE TITLE
[T1 P2] Duda de complejidad de creación de árbol

### ISSUE THREAD

**Issue by Witomi** [IIC2133-PUC/2022-1#116]
Hola!

Sé que la complejidad de la evaluación de colisiones debe ser F*P*log(S), pero tengo dudas respecto a la complejidad que toma crear la estructura del árbol binario, también debe poseer tal complejidad o puede ser mayor, ya que se ejecuta solo una vez?

Gracias

**Comment by CarloGauss33** [comment]
Puede ser mayor. Esto se explico en la ayudantia.

Aca la dificultad es que existen muchas consultas de particula bounce against segment. Por lo que la complejidad de construccion del arbol podria ser S**3 e igualmente no afectaria en casi nada
