### ISSUE TITLE
gitignore repositorio del curso

### ISSUE THREAD

**Issue by diegocostares** [IIC2133-PUC/2022-1#121]
Hola, tengo cargado el repositorio del curso en mi computador, pero como no tienen agregado en el gitignore el '.DS_Store' y el '.vscode', me surgen conflictos cada vez que hago pull. ¿Podrían incluirlo en el gitignore para no tener más problemas? 😥

**Comment by CarloGauss33** [comment]
puedes agregarlo en local y lo tendra en consideracion para pulls

**Comment by diegocostares** [comment]
@CarloGauss33 Lo decía más por qué también note que habían subido varios commit agregando y eliminando ese archivo XD
