### ISSUE TITLE
[T1 P1] Empate en path

### ISSUE THREAD

**Issue by jorge-schenke** [IIC2133-PUC/2022-1#122]
Hola! tengo una duda en los casos de empate para la función PATH(value), en el enunciado dice que al crear el  árbol si hay empate en el criterio utilizado usemos el index para desempatar. Sin embargo, al hacer path, si hay un empate según el criterio, ¿debo retornar el camino al primer nodo encontrado?, ¿o al último?.

Muchas gracias.

**Comment by CarloGauss33** [comment]
Siempre el primero
