### ISSUE TITLE
T1-P2 Distancia entre partículas y segmentos

### ISSUE THREAD

**Issue by andrescf** [IIC2133-PUC/2022-1#125]
Hola! Cuando queremos ver la distancia de una partícula a un segmento ¿se debería considerar la distancia al centro del segmento o el punto mas cercano del segmento a la particula?

**Comment by CarloGauss33** [comment]
No entiendo porque necesitarías calcular eso

**Comment by andrescf** [comment]
Como en el enunciado aparecía que se podía modelar como uno quisiera pensé que podría buscar el segmento mas cercano a cada partícula y ver si colisiona con este, pero al parecer no se puede implementar así. Gracias igual
