### ISSUE TITLE
[Debugging] Problemas en mac

### ISSUE THREAD

**Issue by diegocostares** [IIC2133-PUC/2022-1#126]
Hola, intente desbugear con gdb segun la [guia](https://github.com/IIC2133-PUC/2022-1/blob/master/Gu%C3%ADas/4.%20Gu%C3%ADa%20para%20debuggear%20en%20C.md) y el [video](https://www.youtube.com/watch?v=RNfVQQEUoMQ) que nos subieron, sin embargo estoy teniendo problemas al ejecutarlo. 
En una primera instancia instale gdb (además de la extensión) con
```shell
brew install gdb
```
Ya que el de la guía no funcionaba en mac, luego cree el `launch.json`dentro de `vscode`; sin embargo, al ejecutar F5 me aparecía:
<div align="center">
<img width="289" alt="Captura de Pantalla 2022-04-28 a la(s) 2 35 55 p  m" src="https://user-images.githubusercontent.com/62116423/165823280-dd28bf6d-bca0-4b84-b9cc-d290a9624e6f.png">
</div>
Al darle a depurar de todos modos  me apareció esto: 

<div align="center">
<img width="290" alt="Captura de Pantalla 2022-04-28 a la(s) 2 36 06 p  m" src="https://user-images.githubusercontent.com/62116423/165823299-1897c5ad-2d55-49d3-8a93-8f5c0b47d9c2.png">
</div>

Este contenia `"miDebuggerPath": "/usr/bin/gdb"`, al igual que el el tutorial... Trate cambiándolo a `"miDebuggerPath": "gdb"` pero esto me arrojo otro error (Lo pongo por si acaso):

<div align="center">
<img width="681" alt="Captura de Pantalla 2022-04-28 a la(s) 2 37 10 p  m" src="https://user-images.githubusercontent.com/62116423/165823309-31d5a180-3241-4be9-ac0d-2824d9c733f7.png">
</div>

**Comment by CarloGauss33** [comment]
Problema solucionado

Solucion es:
Para ejecutar el debugger el programa *debe* ser compilado desde mac. No desde docker
