### ISSUE TITLE
[T1-P2] Mostrar visualización Mac

### ISSUE THREAD

**Issue by Joaquin3000** [IIC2133-PUC/2022-1#127]
Hola, todavía no hago ningún cambio en la parte 2, y al correr con Docker me muestra lo siguiente, pero no aparece nada, ni me dice un error. Seguí los pasos de la instalación, y no tuve ningún problema hasta ahora
<img width="707" alt="Captura de Pantalla 2022-04-29 a la(s) 11 35 56" src="https://user-images.githubusercontent.com/80774234/165978630-43a9cf83-03ee-4349-8ac6-39e330ddeeb2.png">

Cuando lo corro directo en el terminal me aparece el error:
(base) MacBook-Pro-de-Joaquin:T1-2022-1-Joaquin3000 joaquin$ ./simulate P2/test_01.txt P2/result.txt
-bash: ./simulate: cannot execute binary file

 Al buscar en internet me dice que el tipo de archivos no es compatible en Mac (https://superuser.com/questions/724301/how-to-solve-bash-cannot-execute-binary-file), y no sé como cambiarlo para hacerlo ejecutable (no quiero cambiar el Makefile y que no funcione).

Si me pueden ayudar muchas gracias!

**Comment by CarloGauss33** [comment]
Lo que pasa es que Docker tiene el objetivo solo de valgrind. Para ver el visualizador deberias compilar y ejecutar desde la terminal de Mac y no desde docker

**Comment by vapina** [comment]
Y cómo hago entonces para correrlo en valgrind y chequear que no hay errores de memoria?

**Comment by CarloGauss33** [comment]
Lo ejecutas en Docker. Pero recuerda que para docker no es necesario que uses el visualizador. Por lo que puedes ejecutarlo con un _--novis_ al final.

**Comment by vapina** [comment]
Mi problema es cuando hago `make`. Me sale el siguiente error: `obj/engine/math/geometry.o: file not recognized: file format not recognized`

**Comment by CarloGauss33** [comment]
Recuerda hacer `make clean` antes de ejecutar make. Para que asi se eliminen archivos antiguos
