### ISSUE TITLE
[T1-P2] Bounding Box Collision

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2133-PUC/2022-1#128]
Hola, estube haciendo unas pruebas. Tengo la siguiente Bounding Box:
![image](https://user-images.githubusercontent.com/69614275/166066958-6eec6d46-46b7-4bd6-9f42-eea71e0f0d43.png)
Y la siguiente particula:
![image](https://user-images.githubusercontent.com/69614275/166067103-586638fd-26c0-4aea-b329-d6097a6b0373.png)
Claramente la particula esta dentro de la caja, pero `particle_boundingbox_collision` me arroja false.

**Comment by Lord-Kelsier** [comment]
Creo que encontre el problema. La funcion clamp:
![image](https://user-images.githubusercontent.com/69614275/166068608-58818e65-7334-48b7-bbd0-ddb09e1126cc.png)

En el enunciado se dice que el min_point es la esquina superior izquierda pero deberia ser la esquina inferior izquierda, analogamente con max_point. Supongo que puedo modificarla cierto?

**Comment by CarloGauss33** [comment]
> Creo que encontre el problema. La funcion clamp: ![image](https://user-images.githubusercontent.com/69614275/166068608-58818e65-7334-48b7-bbd0-ddb09e1126cc.png)
> 
> En el enunciado se dice que el min_point es la esquina superior izquierda pero deberia ser la esquina inferior izquierda, analogamente con max_point. Supongo que puedo modificarla cierto?

Puedes modificar lo que quieras
