### ISSUE TITLE
[T1] Archivos a modificar P2

### ISSUE THREAD

**Issue by nicolecll** [IIC2133-PUC/2022-1#129]
Hola, me surgió una duda respecto a los archivos que podemos modificar en la P2 de la T1. 
En el enunciado dice que debemos modificar src/simulate, sin embargo por como he pensado mi modelación, me sería util hacer algunos cambios en el struct de Bounding Box ¿es posible que haga cambios en esta parte del código?.

**Comment by CarloGauss33** [comment]
Si puedes, aunque no se recomienda
