### ISSUE TITLE
[T1-P2] Problemas visualización

### ISSUE THREAD

**Issue by SofiaP419** [IIC2133-PUC/2022-1#131]
Seguí la guía de instalación y también intente soluciones que aparecen en discord pero me sigue apareciendo este error.
![image](https://user-images.githubusercontent.com/62083532/166130225-d7e89baf-6bd6-42e3-ad30-3cda19a07c47.png)

**Comment by CarloGauss33** [comment]
Ejecuta `make && make clean`
