### ISSUE TITLE
T1-P2 Problemas con el Visualizador

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2133-PUC/2022-1#132]
Mi programa se queda estancado en esta parte y no abriendo el visualizador (cabe recalcar que hice la guía del Set Up; Export display, la extension -ac, y todo): 
![image](https://user-images.githubusercontent.com/69633813/166304646-227df06c-2c34-449e-a190-246ffee5f449.png)

**Comment by ShescBlank** [comment]
No soy ayudante pero pareciera que el otro programa (vcxsrv) ha traído menos problemas a la hora de probarlo. Viste también lo del firewall? Yo estaba igual que tú y eso fue lo que me lo arregló. En el Discord, en dudas-setup, puse un mensaje con todos los pasos que tuve que hacer para lograr hacerlo funcionar.

**Comment by rriveraf** [comment]
gracias crack, tu solución de discord resolvió mi problema
