### ISSUE TITLE
[T1 P2] Coordenadas de segmentos

### ISSUE THREAD

**Issue by mateogs** [IIC2133-PUC/2022-1#133]
Hola, puedo asumir que para cada segmento (pi.x <= pf.x) y que (pi.y <= pf.y) ??

**Comment by rriveraf** [comment]
![Captura](https://user-images.githubusercontent.com/62113699/166610690-feaa5e15-e5cc-45c9-b003-a4bd9392375c.PNG)
Hola!, yo no soy ayudante, pero haciendo un print me di cuenta de que eso no siempre se cumple. te dejo una foto de ejemplo donde se imprimen coordenadas de segmentos.
