### ISSUE TITLE
Test inconsistente

### ISSUE THREAD

**Issue by SugarFreeManatee** [IIC2133-PUC/2022-1#134]
Holis! Al correr mi tare en el servidor el test P1-medium-test-00 tira correct a veces y timeout a veces y esto me tiene preocupado :sob:

**Comment by rriveraf** [comment]
Hola!, yo tengo el mismo problema, a ratos el server tira todos los test de la P1 correctos pero en otros momentos no alcanza a superar P1-medium-test-00 por timeout.
