### ISSUE TITLE
Bounding Boxes de Segmentos

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2133-PUC/2022-1#135]
Hola, en la capsula, se encapsulan los objetos (circulos) con bounding boxes creados en base a sus límites

Pero en el caso se los segmentos me queda a veces que hay nodos con un solo objeto y por tanto su límite es lo que dibuja la linea del segmento (1D) osea la particula nunca esta en la Bounding Box

Cual es la lógica para solucionar esto, bajo que criterio asigno la bounding box? Gracias

**Comment by Lord-Kelsier** [comment]
En `src/engine/math/geometry.h` se define la bounding box, que toma el punto de la esquina inferior izquierda como "min_point" y el de la esquina superior derecha como "max_point" (esta mal escrito). 
![image](https://user-images.githubusercontent.com/69614275/166841577-f271ac14-c489-4119-967d-23b22f32c465.png)
Mientras definas la bounding box asi ya sea que te quede una linea 1D la funcion que determina las colisiones la va a detectar.
