### ISSUE TITLE
[T1-P2] SIGPIPE error

### ISSUE THREAD

**Issue by raibd** [IIC2133-PUC/2022-1#136]
Hola, normalmente me corría la simulación, pero ahora al correr ./simulate con valgrind me da el error `Process terminating with default action of signal 13 (SIGPIPE)` que proviene de la línea `Simulation *sim = simulation_init_from_file(argv[1], visualize);` en `main.c`.

**Comment by cfernandek** [comment]
Hola yo tengo el mismo error, avisa si lo puedes resolver porfa!

**Comment by raibd** [comment]
> Hola yo tengo el mismo error, avisa si lo puedes resolver porfa!

Hola, logre correr el visualizador después de cerrar el Xserver y abrir uno nuevo (con el parametro -ac) y corriendo la línea `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0`. Aunque no estoy seguro si eso elimina el error por completo.
