### ISSUE TITLE
Criterios de aprobación TESTS P2

### ISSUE THREAD

**Issue by bvasquezm** [IIC2133-PUC/2022-1#138]
Hola buenas, tengo dudas sobre cuáles son los criterios de aprobación para la parte 2 de la tarea. Al correrlo en local los tiempos sin visualizador están muy por debajo de los 10 segundos, pero no así con el visualizador. También me entró la duda con la cantidad de memoria utilizada, ya que el intercambio entre memoria y velocidad para los tests entregados dificulta mucho no arrojar MemoryError, incluso liberando prácticamente la totalidad de la memoria. Si la solución cumple con el criterio de complejidad O(n^2 log(n)), ¿Sigue siendo fundamental que pase los tests?

Gracias de antemano.

**Comment by Lord-Kelsier** [comment]
No soy ayudante, pero como lo veo yo para aprobar la parte 2 la ejecucion sin visualizacion debe durar menos de 10 segundos y el output generado debe ser el mismo que el que se entrega como solucion. 
Por el lado de la memoria, en efecto hay un trade off entre velocidad y memoria, la gracia esta en encontrar el equilibrio. Quizas que un hoja contenga varios segmentos en vez de uno.
