### ISSUE TITLE
Diccionario como ABB

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2133-PUC/2022-1#140]
En clases se menciona que implementamos un diccionario como un ABB, como sería esto? pues entiendo que el ABB es una especie de lista ligada con más caminos, y que no se puede acceder a un nodo directamente segun una clave, que es la esencia de un diccionario.

Gracias
<img width="604" alt="image" src="https://user-images.githubusercontent.com/69685161/167318799-c622f691-15f9-4e26-ab4e-f8985c93242e.png">

**Comment by Lord-Kelsier** [comment]
La esencia de un diccionario es el par key, value. Cuando nos digan: "cual es el valor de esta key" hay que encontrarla dentro de las millones que podríamos tener, esa la razón de implementar una forma eficiente de hallarla. Un ABB o una tabla de hash son las opciones que vemos.
