### ISSUE TITLE
[T2] Función de hash incremental

### ISSUE THREAD

**Issue by jadawabe** [IIC2133-PUC/2022-1#145]
Hola, a que se refieren en el enunciado con que una función de hash se pueda calcular de forma incremental? 

Muchas gracias!!

**Comment by diegocostares** [comment]
@carolinamaggi Sigo sin entender muy bien el concepto, ¿Podrías dar algún ejemplo sencillo? Porfis 😢

**Comment by carolinamaggi** [comment]
@diegocostares por ejemplo, digamos que estamos trabajando con palabras y  quieres que tu función de hash le calcule un valor a la palabra ABBA, para calcular el valor de la palabra ABBAC, no necesitas calcular todo de nuevo, necesitas el valor de la palabra ABBA y agregarle algo

**Comment by diegocostares** [comment]
@carolinamaggi Comprendo la formula general se puede expresar asi:
$$\operatorname{hash}(s[i \ldots j])=\sum_{k=i}^{j} s[k] \cdot p^{k-i} \bmod m$$
Pero me surgen enormes dudas a la hora de implementarlo en C, ¿no podrían subir una cápsula sobre esto? En clase solo se mencionó a la rápida y no fue algo que nos detuviéramos.

Ademas, esa formula funciona con el hashin modular, pero si quisiera implementarlo con el método de la multiplicación $h(k)=\lfloor m \cdot(A \cdot k \bmod 1)\rfloor$ no sé cómo adaptar la fórmula.

**Comment by carolinamaggi** [comment]
@diegocostares es parte de la tarea poder hacer investigaciones correspondientes, no te quedes solo con lo de la clase, también puedes investigar más sobre el hash incremental asociados a poblemas de búsqueda, específicamente de patrones, no pienses de manera tan general, usa los número de cada color para poder crear un valor de hash que represente de manera única o casi única una  subimagen_i y que puedas calcular el valor de hash de una subimagen_(i+1) que contenga esta subimagen_i a partir de ese valor
