### ISSUE TITLE
Archivos Input Tarea 2

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2133-PUC/2022-1#148]
Hola, Queria consultar por los archivos input de la Tarea 2, busque en el repo privado y en github pero no encontré, solo estarán disponibles en el servidor?
Que queria saber el tamaño maximo N para poder basear mi extrategia, ya que si no son tan grandes no conviene ir por ciertos caminos.
Saludos cordiales

**Comment by csantiagopaz** [comment]
🥲

**Comment by carolinamaggi** [comment]
Subidos!
