### ISSUE TITLE
[T2] Duda con guardar array por "referencia"

### ISSUE THREAD

**Issue by crow-rojas** [IIC2133-PUC/2022-1#151]
Hola, en la cápsula se mencionó algo de almacenar la matriz NxN por referencia para no usar tanta memoria al guardar toda la matriz, pero no entendí bien el concepto. ¿Me lo podrían explicar? Gracias.

**Comment by Lord-Kelsier** [comment]
el concepto es que podrias guardar una submatriz de 2x2, 3x3,... o NxN en la tabla de hash que represente a las sub imagenes de la camara, pero esto es muy ineficiente. Mejor guardar en un solo sitio la imagen original y en la tabla de hash solo guardar el tamaño y la posicion de la sub matriz en relacion a la original
