### ISSUE TITLE
T2: Usar Matriz como atributo de funcion

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2133-PUC/2022-1#154]
Hola, almaceno mi imagen principal como un array de arrays. Array[ ] [ ]. (Matriz)

Pero tengo problemas al crear funciones que reciban una Matriz como argumento.

void funcion ( int array [ ] [ ] ) no funciona

Pero si funciona cuando asigno un largo fijo con un numero especifico
void funcion ( int array [ 5 ] [ 5 ] ) 

¿Como puedo crear funciones que reciban array de arrays de largo indefinido? Gracias

**Comment by Lord-Kelsier** [comment]
int ** es un puntero de punteros, un Array es un puntero por lo que un Array de Arrays es un puntero de punteros

**Comment by AlfreMK** [comment]
No soy ayudante pero para eso tienes que definir en la misma función la dimensión en el atributo anterior:
ejemplo:
`void function(int dimension, int array[dimension][dimension])`
