### ISSUE TITLE
Invitación Repositorio T2

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2133-PUC/2022-1#156]
Hola,
Estuve revisado mi mail y todavía no me llega una inivtación para el repositorio de la T2, no sé si ya llegó la invitación o no? Si es que me lo pudieran confirmar. En el caso que no hayan sido enviadas, las podrían enviar, porfavor.

**Comment by carolinamaggi** [comment]
Hola, en discord, en el canal de bot puedes pedir una nueva invitación después de registrar tu usuario de github
