### ISSUE TITLE
[Tarea 0] ¿De donde se obtienen locationId y similares?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2133-PUC/2022-1#16]
Hola. Leyendo el Enunciado me surgió la duda de como se asignan los `locationId`, `tableId`, `customerId` e `itemId` a las diferentes entidades que tendremos en el programa.

¿Se asignan estos valores en función de cuantas entidades hay de cada una de forma ordenada?

Por ejemplo si en el archivo de input sale que hay 3 locaciones, con 2, 5 y 4 mesas respectivamente, la ¿modelación sería la siguiente?

Locación 0 --> tiene las mesas Mesa 0, Mesa 1
Locación 1 --> tiene las mesas Mesa 0, Mesa 1, Mesa 2, Mesa 3, Mesa 4
Locación 2 --> tiene las mesas Mesa 0, Mesa 1, Mesa 2, Mesa 3

Saludos!

**Comment by carolinamaggi** [comment]
Los id son directamente entregados desde el archivo de input :)

**Comment by diegocostares** [comment]
@carolinamaggi cuál sería el archivo de input? ¿Lo tengo que crear?

**Comment by carolinamaggi** [comment]
@diegocostares son archivos .txt, les vamos a dar tests para que prueben sus programas, de todas formar si quieres probarlo puedes crear uno tú siguiendo el formato del enunciado

**Comment by diegocostares** [comment]
@carolinamaggi Y cuando los van a subir? Es que no estoy entendiendo como hacerlo

**Comment by Witomi** [comment]
Pueden explicar un poco más el input? La verdad no me quedó claro con los tests

**Comment by carolinamaggi** [comment]
@Witomi te lo explico con el test A_00.txt el primer número N = 22, corresponde a la cantidad de locaciones, después vienen 22 números que corresponden a la cantidad de mesas que hay en cada locación, después un número (S = 1094) que corresponde a las cantidad de instrucciones OPEN-TABLE que van a haber, luego un número (M = 32) que corresponde a la cantidad de platos a agregar a la carta (instrucción MENU-ITEM) y finalmente el resto de eventos. Toda la lectura del archivo de input está implementada en el main, solo debes ocupar las variables entregadas.

**Comment by jrvalenzuela** [comment]
Entiendo como funciona el input.txt, pero es correcto asumir que si existen X mesas en una locación los table_id de esas mesas irán desde el 0 al X-1?

**Comment by francisca0308** [comment]
> @Witomi te lo explico con el test A_00.txt el primer número N = 22, corresponde a la cantidad de locaciones, después vienen 22 números que corresponden a la cantidad de mesas que hay en cada locación, después un número (S = 1094) que corresponde a las cantidad de instrucciones OPEN-TABLE que van a haber, luego un número (M = 32) que corresponde a la cantidad de platos a agregar a la carta (instrucción MENU-ITEM) y finalmente el resto de eventos. Toda la lectura del archivo de input está implementada en el main, solo debes ocupar las variables entregadas.

En la misma línea de esta respuesta, se puede asumir que los MENU-ITEM siempre van a venir ordenados según ID? Creo que no he encontrado ningún Test que no venga así. Esto será siempre así?
