### ISSUE TITLE
[Tarea 0] Estado de la aplicación en el output

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2133-PUC/2022-1#17]
Hola. En la página 6 del enunciado se menciona lo siguiente:

_"Como archivo de output se solicita que se vaya escribiendo el estado de la aplicación según se solicita. Además
luego de finalizar la ejecución de los eventos, se ha de imprimir el estado general de todos los restaurantes,
ejecutando ESTADO MESA para cada mesa de cada establecimiento"_

¿A que se refiere el enunciado con "estado de la aplicación según se solicita"? ¿Nos irán saliendo los eventos `TABLE-STATUS` y `BILL-CREATE` y deberemos imprimir en el archivo de output aquello que se nos indique? ¿o por cada evento que suceda deberemos anotar algo en el output?

Finalmente, quería saber si de casualidad se iban a subir ejemplos de archivos de input y output para probar nuestro código

Saludos :)

**Comment by carolinamaggi** [comment]
Se refiere a que debes imprimir en el archivo de output solo cuando se indique en los eventos.
Se van a subir algunos test y sus output respectivos para que prueben sus programas pero paciencia
