### ISSUE TITLE
[Tarea 0] Invitación a Repo

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2133-PUC/2022-1#21]
Hola! Traté de aceptar la invitación que me llego por mail para entrar a mi repositorio y me dice que la página no está disponible

**Comment by jadawabe** [comment]
A mi me paso lo mismo! :(

**Comment by CarloGauss33** [comment]
Hola, tienen que logearse en github, para que funcione. Si no estan logeados aparecera 404
