### ISSUE TITLE
Tipos Tarea 0

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2133-PUC/2022-1#22]
Hola, buenas tardes/noches

Cuando en enunciado se refiere que todos los números serán enteros, también se refiere a los ID's?
Asumiendo que si, los ID's serán únicos o eso es algo que yo debo me preocupar y chequear?
Los Eventos en mi código deben tener el mismo nombre o puedo cambiarlos? (Ejemplo PERROU-MUERTO -> change_bil )

Gracias de antemano
Saludos Cordiales

**Comment by CarloGauss33** [comment]
Los IDs de los usuarios son unicos. Y los de las mesas son por restaurant.

**Comment by csantiagopaz** [comment]
> 

Yaa perfecto, muchas gracias

**Comment by etoteiza** [comment]
@csantiagopaz No cierres las issues, así la información que tiene puede funcionar a otra persona.
