### ISSUE TITLE
[Tarea 0] Duda eliminar un plato

### ISSUE THREAD

**Issue by jtconcha** [IIC2133-PUC/2022-1#24]
hola! en Condiciones/Supuestos mencionan que para eliminar un plato este debe existir antes, en el caso de que no exista uno, se debe retornar algún output que indique que no se pudo eliminar o simplemente no se hace nada?

**Comment by CarloGauss33** [comment]
Dicho caso borde no existe en ningun test. asi que puedes simplemente no hacer nada
