### ISSUE TITLE
[Tarea 0] Dudas generales id's

### ISSUE THREAD

**Issue by ShescBlank** [IIC2133-PUC/2022-1#25]
Hola :D

Solo para confirmar, si me dicen que hay n mesas, platos  o restaurantes, los ids siempre van a ser de 0 hasta n-1? O puede pasar, por ejemplo, que hay 20 platos y sus ids van del 600 hasta el 619?
Y, por último, pareciera que en los tests los ids de los clientes son por orden de llegada, es decir, el primero que llega tiene id 0, el segundo id 1 y así. Esto siempre va a ser de esta manera?

Muchas gracias 🐧

**Comment by etoteiza** [comment]
En el enunciado se menciona que te daran como input id de mesas, platos, e id location sería la cantidad de restaurantes.

Con respecto a clientes, dice que es universal, así que sería correcto lo que dices.

Saludos!
