### ISSUE TITLE
[Tarea 0] Duda código base

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2133-PUC/2022-1#27]
Hola, viendo el código base de la tarea me pasa que si imprimo N_ITEMS, me aparece el número asociado a S (cantidad de mesas que se van a abrir). No sé si estoy entendiendo algo mal o es un error del código. Gracias!

**Comment by sebastianbreguel** [comment]
Hola! si efectivamente fue un error del código base, ahora mismo estamos trabajando para arreglarlo y decirles que hacer para arreglarlo!

**Comment by fbarrosalcalde** [comment]
Ya perfecto, gracias
