### ISSUE TITLE
[Tarea 0] Parte A.4

### ISSUE THREAD

**Issue by BenjaRubio** [IIC2133-PUC/2022-1#28]
Hola! En la parte que se debe imprimir el TABLE-STATUS, si la mesa esta parcialmente llena, después de imprimir los ID de los clientes se deben poner guiones hasta llenar la capacidad de la mesa?
Además, las indentaciones que hay en ese texto de cuánto son? 4 espacios?
gracias!

**Comment by carolinamaggi** [comment]
@BenjaRubio  Sí, se debe completar con guiones bajos hasta llenar la capacidad.
Después de ESTADO MESA, la indentación es de un tab ("\t"), y luego de CLIENTES otro tab extra

**Comment by BenjaRubio** [comment]
Gracias!
