### ISSUE TITLE
[Duda C]

### ISSUE THREAD

**Issue by BenjaRubio** [IIC2133-PUC/2022-1#29]
Hola, si tengo una función a la que le quiero pasar un array, o una que me retorne un array, para no tener problemas debo pedir memoria? y en ese caso bastaria con eso? Me refiero por que si por ejemplo tengo un array de 3 int nose si estaría correcto hacer lo siguiente:

int array[3];
array = malloc(3 * sizeof(int));

o bastaría solo con la segunda línea?
gracias!

**Comment by etoteiza** [comment]
Hola, depende de donde quieres que esté guardado en la memoria, vale decir, en el stack o heap.
`int array[3];` me dará un array almacenado en stack. `int* array = malloc(3 * sizeof(int));` (Recuerda declarar el tipo de variable) me dará un puntero a un bloque que se encuentra en el heap. 
Espero que con eso se te haya aclarado, saludos!

**Comment by BenjaRubio** [comment]
Entiendo gracias!
