### ISSUE TITLE
[Script] Para correr los tests

### ISSUE THREAD

**Issue by Seon82** [IIC2133-PUC/2022-1#30]
Este script permite correr los tests y mostrar el número de errors para cada difficulta. También guarda los output incorrectos.

Hay que correr el script desde la raíz del proyecto. El primer argumento es el camino hacia la carpeta de tests que contiene `tests` y `solutions`.
Por ejemplo `./run_tests.sh TESTS_T0`.
```
#!/bin/bash
TEST_DIR=${1:-tests}
# Delete old tests
rm -rf "$TEST_DIR/errors";

DIFFICULTIES="easy
medium
hard"

for diff in $DIFFICULTIES
do  
    # Make folder
    mkdir -p "$TEST_DIR/errors/$diff";
    printf "Running ${diff} tests:\n"
    ERRORS=0
    TOT=0
    for in_file in $TEST_DIR/tests/$diff/*
    do
        OUT_FILE="$TEST_DIR/errors/$diff/${in_file##*/}"
        touch $OUT_FILE
        ./ratatouille $in_file $OUT_FILE
        if cmp -s $OUT_FILE $TEST_DIR/solutions/$diff/${in_file##*/}; then
            # If the output is correct, remove file from errors
            rm $OUT_FILE
        else
            ERRORS=$((ERRORS + 1))
        fi
        TOT=$((TOT + 1))
    done
    printf "$((TOT-ERRORS))/${TOT} correct\n\n"
done
printf "=> Output files for the tests that generated errors can be found in ${TEST_DIR}/errors.\n"
```

**Comment by Huasito-Appel** [comment]
Gracias por el aporte 😄

**Comment by diegocostares** [comment]
Hola @Seon82  desde mac no he podido hacer que funcione... cuando lo ejecuto aparece un mensaje de `./ratatouille: No such file or directory`

Cuando hago algunos printf de las carpetas que está leyendo o desde el mismo `${in_file##*/}`, me aparece `*0/1`. Por lo que asumo que el código no me está sabiendo leer los archivos contenidos en los test 😢

**Comment by Seon82** [comment]
Hola, tienes que correr el script desde la carpeta donde está el ejecutable `ratatouille` que generaste con `make`. La carpeta debería parecerse a esto:
```
T0-2022-1-diegocostares/
├── src
├── tests/
│   ├── solutions/
│   │   ├── easy
│   │   ├── medium
│   │   └── hard
│   └── tests/
│       ├── easy
│       ├── medium
│       └── hard
├── ratatouille
└── run_tests.sh
```
Cuando tengas todos los archivos en el buen lugar, deberías poder correr `./ratatouille tests/tests/easy/A_00.txt /dev/null`.

**Comment by diegocostares** [comment]
Lo tengo igual y no me funciona 💔
