### ISSUE TITLE
[Tarea 0] Duda de enunciado y C

### ISSUE THREAD

**Issue by franciscares** [IIC2133-PUC/2022-1#31]
Hola!
 Tengo una duda con el enunciado, en la parte A.1 cuando dice que "puede recibir capacity clientes", ¿ eso quiere decir que ese parámetro se lo podrían o no dar al evento? ¿ o que podría ser un número distinto a cero y siempre se lo entregan?

**Comment by sebastianbreguel** [comment]
Hola! el enunciado se refiere a que el "capacity" que sera entregado define la cantidad de clientes que puede recibir esa mesa, por lo que siempre se entregara ese parametro.
