### ISSUE TITLE
[Duda C] Ejemplo de structs en Ayudantía 0

### ISSUE THREAD

**Issue by fcsanchez** [IIC2133-PUC/2022-1#32]
Hola! probando el ejemplo sobre structs, me surge un error de compilacion sobre que no reconoce las funciones de los structs importados desde los archivos house.c y house.h, lo que me genera duda porque sí se incluye el #include "house.h" en main.c, como también en el house.c y el uso de #pragma once en el house.h

nosé si me faltó agregar algo, pero no logro entender como importar bien structs

Edit: me di cuenta que el error era porque no estaba anunciando la compilación del archivo house.c :(, usando el comando completo gcc main.c house.c -o probando_struct funciona

**Comment by Huasito-Appel** [comment]
Suele suceder que tenemos errores por no usar el comando o que tenemos malos los paths de las carpetas.
Para la tarea por suerte contamos con el ```Makefile```por lo que no vas a tener que preocuparte por eso.
