### ISSUE TITLE
[Tarea 0] Duda sobre apertura de mesas

### ISSUE THREAD

**Issue by jordonezp** [IIC2133-PUC/2022-1#33]
Hola! Me surgió una duda respecto a si es que las m<sub>i</sub> mesas que tiene la locación i comienzan todas abiertas y que luego se van agregando (y abriendo) más mesas mediante el evento ``OPEN-TABLE``, o si es que las m<sub>i</sub> mesas de una locación comienzan todas cerradas y se van abriendo algunas de ellas mediante el evento ``OPEN-TABLE``. Me parece que la segunda opción es la correcta pero prefiero asegurarme dado que nunca se dice explicitamente que las mesas de una locación parten abiertas o cerradas. De antemano muchas gracias!

**Comment by jordonezp** [comment]
Ok, muchas gracias por tu ayuda Seba 🙏🏽

**Comment by catalina-ramirez** [comment]
Hola! Tengo una duda respecto a esto. Si la mesa está cerrada, igual se imprime su estado al final? No entiendo mucho la utilidad de las mesas cerradas, ya que al parecer no se manejan casos como en los que una persona quiere entrar a una mesa cerrada.

**Comment by sebastianbreguel** [comment]
Creo que te podria servir revisar la [issue](https://github.com/IIC2133-PUC/2022-1/issues/56) que preguntan sobre algo parecido
