### ISSUE TITLE
[Setup] Mac M1 problema VirtualBox

### ISSUE THREAD

**Issue by MariaJoseCovarrubias** [IIC2133-PUC/2022-1#36]
Hola! Me acabo de cambiar de computador y tengo este problema al instalar VirtualBox. No he sabido cómo solucionarlo! 

<img width="439" alt="Captura de Pantalla 2022-03-16 a la(s) 19 20 40" src="https://user-images.githubusercontent.com/54035477/158700980-52c703a8-6f08-42b3-a6a4-731669a15e20.png">

**Comment by CarloGauss33** [comment]
Hola @MariaJoseCovarrubias , Si tienes un mac M1 te recomiendo fuertemente que uses docker y no VirtualBox. esto es porque virtualbox no esta muy actualizado para la nueva arquitectura. 
No deberias tener ningun problema con el setup de docker ya que es el mejor camino para usar via Mac con M1
