### ISSUE TITLE
[T0] Reusar el código de la ayudantía para listas ligadas

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2133-PUC/2022-1#39]
Hola! Quería saber si podíamos usar el código de la ayudantía textual en nuestra tarea. En particular quería usar el código de las listas ligadas. Este código es super corto y básico, por lo que según yo es casi imposible no copiarlo, pero quería confirmar que no habría problema con ustedes.

Saludos,

**Comment by BMarink512** [comment]
Hola, puedes usarlo.

Las referencias que uses indícalas en el readme. Algo como mis referencias son [ayudantia/link]
