### ISSUE TITLE
[T0] Significado de la palabra "imprimir"

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2133-PUC/2022-1#41]
Hola! Que en el enunciado, en múltiples partes sale que se debe "imprimir" algo. Por ejemplo, en la sección B2 se lee:

"Y se ha de imprimir el ID del elemento eliminado de la siguiente forma:
DEVOLUCION itemID"

¿Con "imprimir" se refiere a que se debe escribir en el texto output.txt o se refiere a que se debe imprimir por consola?

**Comment by sebastianbreguel** [comment]
Si con imprimir, se refiere a escribirlo sobre el archivo output.txt
