### ISSUE TITLE
[Duda C]

### ISSUE THREAD

**Issue by BenjaRubio** [IIC2133-PUC/2022-1#42]
Hola, si hago lo siguiente:

int* a = malloc(sizeof(int));
int* b = a;
free(a);

Luego, ¿la variable b sigue teniendo la dirección de memoria que tenía antes aunque ya no me sirva o queda en NULL?
Gracias!

**Comment by CarloGauss33** [comment]
Continua almacenando la direccion de memoria. Solamente que al tratar de acceder a dicha direccion te encontraras con u `segfault`
