### ISSUE TITLE
Empate en BILL-CREATE

### ISSUE THREAD

**Issue by fedezang** [IIC2133-PUC/2022-1#45]
Hola!
estaba revisando las soluciones a los test, y me di cuenta que cuando hay un empate entre clientes, no se elige al de menor id como dice el enunciado.

Por ejemplo en el test easy C_01, donde debería ser el cliente 399 el que pidió mas platos:
BOLETA MESA 5:0
	PEDIDOS
		PERSONA 399
			4 1486
		1486
		FIN PERSONA
		PERSONA 499
		0
		FIN PERSONA
		PERSONA 438
			0 1009
		1009
		FIN PERSONA
		PERSONA 439
			6 157
		157
		FIN PERSONA
		PERSONA 440
		0
		FIN PERSONA
	FIN PEDIDOS
	EL CLIENTE 438 PIDIO MAS PLATOS
	EL CLIENTE 399 GASTO MAS
	EL CLIENTE 440 GASTO MENOS

Me parece que lo mismo pasa en otros test, por si lo podrían cambiar.

Gracias!

**Comment by carolinamaggi** [comment]
Arreglado :)
