### ISSUE TITLE
[T0] Modelación clientes en una mesa y comparación con tests

### ISSUE THREAD

**Issue by AlfreMK** [IIC2133-PUC/2022-1#47]
Hola, mi problema es que al modelar los clientes en una mesa lo hice con una lista ligada, lo que al principio no debería parecer un problema, sin embargo, el momento de crear y llevarse a cabo el evento de `PERROU-MUERTO`, lo que se printea en el `TABLE-STATUS` de los tests depende de la modelación. A modo de ejemplo, supongamos que se tiene un `TABLE-STATUS` siguiente:
```
ESTADO MESA 0:0
	4
	1
	CLIENTES
		0
		1
		2
		_
FIN ESTADO
```
Luego, al realizar `PERRO-MUERTO 0 0 1`, con lista ligada lo que se tendría sería:
```
ESTADO MESA 0:0
	4
	2
	CLIENTES
		0
		2
		_
		_
FIN ESTADO
```
Ahora, si cambiamos la modelación a usar arrays (que es como lo modelaron para realizar las solution tests), lo que se tendría sería:
```
ESTADO MESA 0:0
	4
	2
	CLIENTES
		0
		_
		2
		_
FIN ESTADO
```
Dejando los resultados de los primeros tests como inválidos, pues entregan output distinto.

Realizar el cambio de lista ligada a array no sería un problema si no fuera por que tendría que cambiar prácticamente la mitad de mi código por estar modelado de forma distinta, lo que al final se traduce en un consumo de tiempo.

Mi duda es, ¿los tests finales que se utilizarán para revisar la tarea tendrán contemplada los dos tipos de modelación o solo la de arrays?

Gracias de antemano y perdón por el mucho texto.

**Comment by carolinamaggi** [comment]
Puedes hacerlo como quieras, el problema de la modelación es que el cliente se sienta en el primer asiento disponible según enunciado, de modo que si algún cliente llega después de que se hace perro muerto debería sentarse ahí ya que es el asiento disponible. Si lo haces con lista ligada deberás hacer algo para saber cual es el asiento disponible.
