### ISSUE TITLE
[T0] Makefile

### ISSUE THREAD

**Issue by Seon82** [IIC2133-PUC/2022-1#48]
Hola! Se permite modificar el nivel de optimización en el Makefile?

**Comment by ShescBlank** [comment]
Holaaa, justo también quería preguntar si se podía cambiar. 

En el makefile se menciona que es recomendable solo cambiar el OPT, como entre la opción que no optimiza para debugear y la que optimiza al máximo.

Además, en particular, cuando pongo el OPT en la opción que optimiza, el make me tira un par de warnings de que puede haber variables no inicializadas (con el otro makefile no ocurría), pero esto no debería pasar dado el flujo del programa. Me debería preocupar de esos warnings aunque los tests funcionen bien?

Muchas gracias :D

**Comment by carolinamaggi** [comment]
No importa, son warnings de declaración, el compilador los salta :)

**Comment by CarloGauss33** [comment]
@Seon82, Si, ningun problema con que modifiquen el nivel de optimizacion. Aunque ojo, deberia ser lo unico que cambien del makefile. En caso de que modifiquen algo mas y su programa no compile en la correccion, es responsabilidad de ustedes
