### ISSUE TITLE
[C] Duda sobre Modularización

### ISSUE THREAD

**Issue by raibd** [IIC2133-PUC/2022-1#50]
Hola, tengo una lista ligada L1 digamos, y quiero agregarle otra lista ligada L2 a cada nodo de L1. Mi duda es como manejar la importación de archivos, asumiendo que defino cada struct en sus archivos `.h` y `.c` separados. En este caso, si quiero poder agregar un `struct L2*` dentro de la declaración de L1, tengo que incluir la línea `#include "L2.h"` en el archivo `L1.h`? 
Por último, cómo se si escribir `#include "file"` vs `#include <file>`?

Gracias de antemano

**Comment by carolinamaggi** [comment]
@raibd sí, debes incluir la línea #include "L2.h" en el archivo L1.h
 Cuando sean módulos creador por ti  es con #include "file" (módulos locales).
#include <file> son módulos globales instalados en el computador.
