### ISSUE TITLE
[Servidor] Wrong Output pero diff me arroja que son iguales

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2133-PUC/2022-1#52]
Hola, hice una solicitud de test en el servidor y me arrojo a todos Wrong output, sin embargo, he revisado algunos outputs usando diff con los ultimos que enviaron (19 marzo) y no existen diferencias. 
Probé hacer un clone a mi repositorio en otro sitio para que se ejecutara limpiamente y aun asi los diff me dicen que son identicos.

**Comment by carolinamaggi** [comment]
@Lord-Kelsier Acabo de revisar tu repo y no has hecho push, los últimos commits son de Carlos, por lo tanto el servidor revisa esos archivos base y el output queda vacío

**Comment by Lord-Kelsier** [comment]
Cierto, me acabo de dar cuenta que estaba subiéndolo a un fork que hice. Gracias
