### ISSUE TITLE
[Tarea 0] Duda servidor

### ISSUE THREAD

**Issue by Witomi** [IIC2133-PUC/2022-1#53]
Hola!

Acabo de probar mi código en el servidor, y me aparece `MemoryError -> Tu programa utiliza mas de 1.2GB de Ram o Arroja SegFault`, sin embargo, al correr en local con valgrind me aparece que ocupo menos que esa memoria para cualquiera de los tests, y no poseo problemas de segmentation fault, corren todos los tests correctos. 

Mi duda es si esos 1.2 GB son para cada test o para todos en conjunto?

Y a pesar de que me salgan correctos todos los tests al correrlo en el servidor, me aparece `Wrong Output -> Tu output no cumple con los criterios minimos de aprobacion`, esto se gatilla por el mensaje anterior o por qué?

Gracias!!

**Comment by carolinamaggi** [comment]
Hablas del glosario de abajo? eso es solo para hacerles saber el significado de lo que les puede salir en resultados, si en la tabla tu resultado sale CORRECT en todo, entonces está bien

**Comment by Witomi** [comment]
ups jajajaja gracias!!
