### ISSUE TITLE
[T0] Debuggear en Mac

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2133-PUC/2022-1#54]
Hola! Estoy intentando debuggear mi código usando la guía que está en el repositorio y vscode, pero al intentarlo me tira el siguiente error: "Unable to start debugging. The value of miDebuggerPath is invalid"
Tengo mac y ya instalé gdb y no sé qué puede ser :(

**Comment by etoteiza** [comment]
Cómo configuraste el `launch.json`?

**Comment by etoteiza** [comment]
Y que error te sale ?

**Comment by beatrizacuna** [comment]
> Cómo configuraste el `launch.json`?

Igual como salía en la guía del curso

**Comment by beatrizacuna** [comment]
> Y que error te sale ?

"Unable to start debugging. The value of miDebuggerPath is invalid"

**Comment by etoteiza** [comment]
Creo que me pasó ese mismo error, debes buscar el path de gdb, que puede ser distinto al que está en la guía. si no lo sabes puedes buscar ejecutando `whereis gdb` en terminal (en mi caso es `/usr/local/bin/gdb`) y ponerlo en esa parte de miDebuggerPath.

Me cuenta si lo pudiste arreglar, saludos!
