### ISSUE TITLE
[Valgrind con Docker] Duda sobre clonar repositorio con git

### ISSUE THREAD

**Issue by vapina** [IIC2133-PUC/2022-1#55]
Hola!

Tengo Mac y me gustaría clonar mi repositorio de las tareas dentro de la carpeta `/valgrind-docker/volumes` para correr mi tarea con valgrind y no tener que copiar y pegar los archivos todo el tiempo. 

Intento instalar git con `sudo apt-get install git-all` pero me tira el siguiente error: `bash: sudo: command not found`.

No entiendo cómo funciona el contenedor, si este es linux o no y si sería posible clonar el repositorio desde ahí.

**Comment by adbakulic** [comment]
Hola! 

Se puede simplemente copiar y pegar los archivos de mi tarea en la carpeta volume? y si no cómo puedo copiarlas?
O como puedo correr mi tarea que esta en la carpeta T0_edd desde volume que está en la carpeta valgrind-docker?

Gracias!
