### ISSUE TITLE
Duda caso borde

### ISSUE THREAD

**Issue by Araos827** [IIC2133-PUC/2022-1#56]
Hola! Dos cosas. Quería saber si es que luego de todos los OPEN-TABLE quedan todas tables abiertas, o puede pasar que haya algun restaurant por ejemplo que tiene N mesas pero que entre los OPEN-TABLE se le mande a abrir menos que N?

De ser el caso, podria un evento tipo CUSTOMER querer sentarse en un a table que no se haya abierto?

Nuestro programa debe poder manejar eso?

**Comment by sebastianbreguel** [comment]
Hola! Si, todas las mesas dentro de un restauran seran abiertas, por lo que no es posible que un CUSTOMER se quiera sentar en una que no se haya abierto!
