### ISSUE TITLE
[Tarea 0] Duda caso borde PERROU-MUERTO

### ISSUE THREAD

**Issue by pwillmer** [IIC2133-PUC/2022-1#57]
Hola! tengo dudas sobre los casos borde de este evento.
1. Solo habrá PERROU-MUERTO si es que hay 2 o más clientes en la mesa?
2. Puede hacer PERROU-MUERTO el primer cliente que llega a esa mesa? o solo es posible a partir del segundo cliente en adelante.

**Comment by sebastianbreguel** [comment]
Hola! a la respuesta a tus preguntas:
1.-  Si, solo en mesas donde haya 2 clientes se realizara.
2.- No, desde el segundo cliente en adelante es el que podra hacer PERROU MUERTO
