### ISSUE TITLE
[Tarea 0] como reasignar platos al hacer PERROU-MUERTO

### ISSUE THREAD

**Issue by jrvalenzuela** [IIC2133-PUC/2022-1#59]
Cuando un cliente hace perrou-muerto, sus platos se asignan al primer cliente de la mesa. Dado que el orden de los platos importa para funciones como order-cancel, como se asignan los platos? Es decir, en caso de que el primer cliente haga order-cancel, se borraría el último pedido que correspondía a el primer cliente, o el último pedido del cliente que hizo perrou-muerto?

**Comment by carolinamaggi** [comment]
Los platos se anexan al final de los platos del primer cliente, por tanto en caso de darse la situación se haría order cancel al último plato que queda
