### ISSUE TITLE
Error al Clonar repositorio

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2133-PUC/2022-1#62]
Hola! No me deja clonar mi repo en mis carpetas en WSL, sí pude clonar el syllabus.  Que puede ser? Gracias!

<img width="725" alt="image" src="https://user-images.githubusercontent.com/69685161/159396852-0d9fba30-01e4-4705-b5db-6b86efda274f.png">

**Comment by JoseTomasSoto** [comment]
La password esta bien y todo

**Comment by sebastianbreguel** [comment]
Hola Jose tomas! el error se debe a que github pide que uses un token, que debes crear en la pagina web. 

Esta [guía](https://docs.github.com/es/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) que encontré debería servirte!

Luego de esto, esta será la contraseña cuando hagas git clone, push o pull; y te pida autorización.
