### ISSUE TITLE
Problema para correr los tests

### ISSUE THREAD

**Issue by javialf123** [IIC2133-PUC/2022-1#63]
Hola, tengo un problema cuando intento correr los tests en la tarea. Agregué la carpeta TESTS-T0 a la carpeta T0-BASE y cuando intento compilar el código (estoy probando el código que se nos entregó sin ningún cambio), logra compilar con el "make" pero al ejecutar el comando "./ratatoille input output" me entrega un segmentation fault y no ocurre nada mas!!

**Comment by etoteiza** [comment]
Estás poniendo bien el path del input y output? puede pasar que no se le esté dando bien el path a los tests del input

**Comment by Huasito-Appel** [comment]
@javialf123 , a que te refieres con corre bien ? , el programa se cae automaticamente si no detecta archivos de input, output.
revisa lo que dice edu, el comando de ejecución se debería ver algo asi  ```/ratatoille test/easy/easy_0.txt out.txt``` . Tener en cuenta que tienes que pasar de buena forma el path, desde src , para ambos .txt.
