### ISSUE TITLE
Error al inicializar lista ligada

### ISSUE THREAD

**Issue by fbesoainp** [IIC2133-PUC/2022-1#65]
Hola tengo este error " error: initializer element is not constant " cuando intento inicializar una lista ligada igual a la de la ayudantía.

**Comment by fbesoainp** [comment]
Ya encontre el error. 
Aqui se explica mejor por si a alguien le interesa: https://stackoverflow.com/questions/35962921/initializer-element-is-not-constant-in-c

Básicamente tenia que ponerlo dentro de una función, por ejemplo main.

**Comment by carolinamaggi** [comment]
Que bueno que hayas podido solucionar tu problema, te borré las fotos porque no se puede subir fotos de tú código, si necesitas ayuda de este estilo que necesitas mostrarnos el código es más fácil que preguntes por discord y algún ayudante te contactará
