### ISSUE TITLE
[C] Duda con tipo de nodo en listas ligadas

### ISSUE THREAD

**Issue by crow-rojas** [IIC2133-PUC/2022-1#67]
¡Hola!

Tenía una duda sobre la implementación de listas ligadas. La lista ligada base que vimos en la ayudantía en sus nodos almacenaba un int, ¿pero qué pasa si en un nodo quiero almacenar otro tipo, por ejemplo, un struct? ¿Tengo que redefinir nuevamente tanto el struct del nodo como de la lista ligada como tal? ¿O hay alguna forma de hacerlo más eficiente?

¡Gracias!

**Comment by etoteiza** [comment]
No hay otra forma más eficiente, es precisamente como lo dices. El nodo en general tiene 2 cosas como mínimo que almacenar: un puntero al siguiente nodo y la información a contener. Lo último puede ser int (o varios), char, u otro struct. y la definición de lista ligada no debería cambiar, es decir, seguiría necesitando almacenar un puntero a head y tail.
