### ISSUE TITLE
Duda formato de outputs

### ISSUE THREAD

**Issue by jorge-schenke** [IIC2133-PUC/2022-1#68]
Hola, tengo una duda en cuanto a como se van a corregir los outputs.}

Tenemos que hacer que los outputs tengan exactamente el mismo formato de los outputs que nos entregaron? por ejemplo, al imprimir una mesa vacía, es necesario que se impriman puros "_" o puedo imprimir "MESA VACÏA"? también me pasa que me hace más sentido por ejemplo imprimir las 2 personas que están sentadas solamente en vez de las dos personas y después miles de "_".
Van a corregir según correctitud de los outputs o simplemente comparando carácter por carácter?.

Gracias!

**Comment by carolinamaggi** [comment]
@jorge-schenke Tienen que ser exactamente iguales
