### ISSUE TITLE
Dudas perro muerto

### ISSUE THREAD

**Issue by jorge-schenke** [IIC2133-PUC/2022-1#69]
Hola, tengo unas dudas en cuanto al funcionamiento de PERROU-MUERTO:

1. ¿Al hacer perro muerto se elimina a la persona de la mesa para futuras boletas?.
2. ¿Si no fuese así, en la boleta los platos le corresponden al perro muerto o a quien los recibió a la hora de ver quien pidió más/menos?

Gracias.

**Comment by sebastianbreguel** [comment]
Hola!, respondiendo a tus preguntas:
1.- si, el cliente que hace perro muerto, no aparecerá en la boleta
2.- Creo que fue respondida en la 1
