### ISSUE TITLE
[T0] Perro puerto en mesa con una persona

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2133-PUC/2022-1#72]
Hola! Quería saber si es que se puede dar el caso de que un cliente haga perro muerto estando solo en la mesa?
En caso de que esto pueda ocurrir, ¿la cuenta del cliente simplemente desaparece y el restaurant asume las péridas?

**Comment by sebastianbreguel** [comment]
Hola!, no debería poder suceder un perro muerto a menos que hayan 2 personas sentadas

**Comment by Araos827** [comment]
Hola! Con no debería poder suceder te refieres a que nuestro programa debe saber manejar ese caso borde o que en los tests no va a venir ese csao?

**Comment by sebastianbreguel** [comment]
Ningun test hara que esto suceda
