### ISSUE TITLE
[T0] Orden de ItemId en Bill Create

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2133-PUC/2022-1#73]
Hola! Que en la sección B3 BILL-CREATE no se especifica en qué orden se deben imprimir los ItemId de los productos que pidió cada cliente. ¿Se ordenan en orden ascendente, descendente, de más barato a más caro, desde el pedido más recientemente hasta el pedido más tarde (o viceversa), etc.? Me imagino que es importante el orden para que el output coincida con el output de los tests. 

Saludos,

**Comment by sebastianbreguel** [comment]
Hola! Se deben imprimir en el orden en que fueron pedido los platos

**Comment by raimundomartinez** [comment]
Pero, ¿uno va desde el más reciente hacía el más viejo o viceversa?

**Comment by sebastianbreguel** [comment]
Hola!, del mas viejo a mas reciente
