### ISSUE TITLE
[T0] Primer cliente perro muerto

### ISSUE THREAD

**Issue by BelenMadariaga** [IIC2133-PUC/2022-1#74]
Hola, empecé a dudar con a qué se refieren con el primer cliente. 

Si bien los clientes se van sentando en el primer asiento disponible, ¿qué pasa en una mesa con 2 personas y quien hace perro muerto es el que está en el primer asiento?, ahí el primer cliente sería el que está en el asiento siguiente? En otras palabras, puede el primer cliente hacer perro muerto?

**Comment by sebastianbreguel** [comment]
Hola! a la respuesta a tus pregunta, esto no puede pasar, ya que desde el segundo cliente en adelante es el que podra hacer PERROU MUERTO
