### ISSUE TITLE
[T0] Recomendación de Algoritmo Sort

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2133-PUC/2022-1#75]
Hola! Que para la parte final de la tarea, es necesario ordenar las Tables en base al location_id y table_id. Quería saber si nos recomiendan algún algoritmo de Sort visto en clases para hacer esta tarea. Sería de gran ayuda para no perder tiempo programando funciones que despues uno no termina usando.

Saludos,

**Comment by carolinamaggi** [comment]
@raimundomartinez No te preocupes, se entregan ordenados

**Comment by raimundomartinez** [comment]
¿Estas segura que las mesas se entregan ordenadas? Porque el orden en que se abren las mesas usando OPEN-TABLE es al azar, por lo que se tendrían que ordenar las mesas para poder respetar "el orden de id de restaurantes
y mesas" que es lo que sale en el enunciado.

**Comment by carolinamaggi** [comment]
Es cierto, a lo que me refería es que desde el principio con open-table insertaras la mesa en el orden que corresponde el id, ya que siempre serán desde 0 a la capacidad del restaurante
