### ISSUE TITLE
[T0] PERROU-MUERTO y posterior asiento vacío en el medio.

### ISSUE THREAD

**Issue by Francisco-Morales-R** [IIC2133-PUC/2022-1#77]
Hola, ¿Se podría dar el caso en que una persona haga perro muerto, dejando un espacio vacío entre dos personas en la mesa, y que luego llegue otra persona a esa mesa y se tenga que sentar ahí y no al final?

**Comment by sebastianbreguel** [comment]
Hola! si, en (esta issue)[https://github.com/IIC2133-PUC/2022-1/issues/47] un alumno pregunto lo mismo, mostrando un caso.
