### ISSUE TITLE
Problema con los frees

### ISSUE THREAD

**Issue by javialf123** [IIC2133-PUC/2022-1#78]
Hola, tengo un problema al crear los frees en mi programa. Tengo structs que a su vez tienen como atributos listas de structs y no se como ir cerrandolos al terminar!!

**Comment by PedroFuenzalida** [comment]
Hola! Te recomiendo que dentro de la función de _destroy_ de tu _struct_ ejecutes en primer lugar las funciones de _destroy_ de los _structs_ que estan contenidos en la lista.

**Comment by Huasito-Appel** [comment]
Tal y como recomienda @PedroFuenzalida , si tienes elementos que contienen a su vez otros, debes ir liberando de "adentro hacia fuera ", piensalo como una [Matrioska](https://en.wikipedia.org/wiki/Matryoshka_doll) , debes acceder desde tu struct "superior / grande " al mas pequeño, para primero liberar los pequeños -> mediano -> grande.
