### ISSUE TITLE
clonar repo del curso en mac

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2133-PUC/2022-1#8]
Hola! Estoy usando mac y me quedó la duda de si debo clonar el repo del curso dentro de la carpeta `volume` perteneciente a `valgrind-docker`

**Comment by Huasito-Appel** [comment]
hola Margarita, no es necesario.
dentro de ```volume```vas a clonar tus repositorios ( que te generaremos ) para realizar tus tareas, ahora si te interesa correr el código que subamos, basta con que muevas a ```volume```la carpeta que contenga estos archivos, por ej el de una ayudantía .

**Comment by Margarita-Paz** [comment]
Genial! mañana en la ayudantía habrá alguna instancia para ayudarnos a usar la máquina virtual?
