### ISSUE TITLE
[T0] Duda Order-Create

### ISSUE THREAD

**Issue by valerianazal** [IIC2133-PUC/2022-1#86]
Hola! ¿Qué hay que hacer si se entrega un ID de una mesa donde no está sentado el cliente?
Al correr el test fácil C_01.txt, se debe sentar al cliente 167 en la mesa 10. Luego, cuando se pide crear una orden para dicho cliente el ID de la mesa que se entrega es el 11, donde no se encuentra ese cliente, por lo que no sé qué debo hacer en ese caso.

Gracias de antemano :)

**Comment by carolinamaggi** [comment]
hay un change-seats antes de la orden y se cambia a la mesa 11
