### ISSUE TITLE
Instalación de la librería gráfica GTK+

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2133-PUC/2022-1#97]
Hola ! Corrí sudo apt-get install libgtk-3-dev en Ubuntu y me tira este error al final. ¿Está bien? Por lo que veo se alcanzaron a descargar cosas pero no todo.

![image](https://user-images.githubusercontent.com/62180259/163289028-41c3c01c-d7f6-46cb-ba43-d1290cc04f85.png)

Saludos,
DS

**Comment by FelipeLara00** [comment]
Hola! 
Tenia el mismo problema y usando el comando **sudo apt-get update** se me arreglo!
