### ISSUE TITLE
error calling PR_SET_PTRACER, vgdb might block

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2133-PUC/2022-1#98]
Hola! Al correr valgrind tengo este problema. En internet dicen que no es un error común y debo correr Bugzilla. Que puedo hacer? Gracias.

**Comment by CarloGauss33** [comment]
No es un error. Es problema de valgrind. No deberias hacer nada ya que no afecta el funcionamiento de valgrind. Igualmente te mostrara los leaks u errores de memoria
