### ISSUE TITLE
[T1-P1] Valores iguales

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2133-PUC/2022-1#99]
Hola, una duda.
Yo iba a hacer un arbol con 3 hijos, los mayores, los menores y los iguales, pero dado que se nos pide que sea un BTS puedo hacerlo? Si es que no se puede los valores iguales irian a la izquierda o la derecha? esto ya que en ambos casos con la operacion delete puede dar distintos outputs dependiendo de donde se pongan valores los iguales

**Comment by etoteiza** [comment]
Se pide implementar un BST, por lo que debería de tener 2 hijos. En el caso de valores iguales, como se menciona en el enunciado, es por orden de input. Eso significa que ha de ir a la derecha por orden.

**Comment by Lord-Kelsier** [comment]
muchas gracias
